# Generated by Django 2.2.4 on 2020-04-08 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_title', models.CharField(blank=True, max_length=200)),
                ('page_title', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_title', models.CharField(blank=True, max_length=15, null=True)),
                ('page_title', models.CharField(max_length=200)),
                ('sub_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Page')),
            ],
        ),
    ]
