# Generated by Django 2.2.4 on 2020-04-08 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submenu',
            name='sub_menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child', to='app.Page'),
        ),
    ]
